version: 2.1

executors:
  ubuntu_vm:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true

jobs:
  test:
    executor: ubuntu_vm
    steps:
      - checkout
      - run: make test
      - store_artifacts:
          path: target/cucumber-html-reports

workflows:
  run_test:
    jobs:
      - test